### ISSUE TITLE
Autostart must be an option

### ISSUE THREAD

**Issue by yfxwardy** [zidoro/pomatez#124]
Autostart, certainly, must be an option in settings

**Comment by roldanjr** [comment]
You can disable `Auto-start Work Time` if you wish.

**Comment by yfxwardy** [comment]
@roldanjr I mean autostart program with windows start

**Comment by roldanjr** [comment]
If you're using Windows, just go to Task Manager > Startup and find the app name then right click and disable it.

I will try to figure it out how to dynamically toggle that features using the renderer process.
