### ISSUE TITLE
Windows Defender warns of trojan (Portable Version 1.1.0)

### ISSUE THREAD

**Issue by hugo-laestander** [zidoro/pomatez#135]
I downloaded the portable version from releases. Windows Defender warns of trojan and automatically deletes the file. But the non-portable setup file had no warnings and installed correctly.

![image](https://user-images.githubusercontent.com/45902093/99392851-ade03400-28dc-11eb-930d-55a29d6cb431.png)
![image](https://user-images.githubusercontent.com/45902093/99393282-67d7a000-28dd-11eb-8421-3444c0d3c8cc.png)

System info:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by roldanjr** [comment]
I honestly don't know about that @ReleaseTheKnowledge
That might because the app was not signed.
