### ISSUE TITLE
Feature: Press ctrl+enter to add tasks

### ISSUE THREAD

**Issue by kleber-swf** [zidoro/pomatez#172]
It would be nice to press ctrl+enter to add tasks to the list.

It's a minor issue, I know, but it would be faster and easier to add tasks.

**Comment by barleymalt** [comment]
upvote

**Comment by sekwah41** [comment]
While this is the original task, this is closed in favor or #271 as it has more detail of possible variations of the key combos. Though I will be adding this :)
