### ISSUE TITLE
Bug Report: Flickering Timer Bar

### ISSUE THREAD

**Issue by carafelix** [zidoro/pomatez#268]
**Describe the bug**
The timer bar element is flickering when the mouse hovers over the timer tab controls.

**To Reproduce**
    Open the Pomatez app, starting a new session
    Go to 'the Timer' tab
    Before starting the timer / with a full timer bar.
    Hover mouse over play, restart, forward, volume or sessions clickable elements.
    The timer bar element will exhibit visual distortion / flickering behavior.

**Expected behavior**

    The timer bar should remain static so long as the timer has not started.
    The timer bar should not be missing arbitrary sections.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/48109042/170586390-376592f4-ac8c-47d2-b840-cce5437acccd.png)

**Desktop (please complete the following information):**

    OS: Linux (Ubuntu)
    App Version 22.04 LTS
    Installer  ubuntu snap store

**Additional context**

**Comment by sekwah41** [comment]
We've seen some other issues with ubuntu mostly after waking from hibernation. 

We've upped the electron version which may help with this as we cant directly do anything else to try to fix this though I need to make some style changes which are blocking the update release.

**Comment by roldanjr** [comment]
Is this issue still persist with the latest released version @carafelix ?

**Comment by carafelix** [comment]
@roldanjr sorry for the late response. As of today in the snap version (1.2.2), the artefact is gone. Working as intended!

**Comment by sekwah41** [comment]
Perfect :D
