### ISSUE TITLE
Framework migration/Dual Support

### ISSUE THREAD

**Issue by TishanV** [zidoro/pomatez#282]
**Is your feature request related to a problem? Please describe.**
As I know Electron is a great framework for cross-platform apps but it's downfall is that it uses Chromium which takes lot of RAM and app bundle size. Since Pomatez app is light unlike VSCode try considering migrate to other lightweight frameworks like Tauri or Neutralino.js.

**Comment by TishanV** [comment]
If you are okay with it assign me to this issue.

**Comment by roldanjr** [comment]
> If you are okay with it assign me to this issue.

Hi @TishanV , I'm good with that as long as the project will benefit from that.

What do you think @sekwah41 @gillisandrew?

**Comment by sekwah41** [comment]
I'm quite open to looking into Tauri. I've actually been considering doing it for this app as a practice anyway.

As we have little to no direct desktop code other than revising and a few other things I don't believe this would be a major change and we can reuse most basically all the front-end stuff.

Only reason I've not looked before is being tied up with some other projects or my other projects would require a full redo of the code signing phase.

Only thing I think we'd need to look into is how to get Tauri apps on the snap store or automate that.

**Comment by sekwah41** [comment]
Only part is the backend would be in rust which shouldn't be complex anyway as from what I've seen the framework is pretty clean and makes small bundles.

**Comment by sekwah41** [comment]
I've also pinned this issue as it would be quite a major one that would render some of the backlog of bugs redundant.

**Comment by sekwah41** [comment]
In case anyone has not seen Tauri https://github.com/tauri-apps/tauri

**Comment by roldanjr** [comment]
> In case anyone has not seen Tauri https://github.com/tauri-apps/tauri
> 
> And an example of how they are progressing, they have an experimental snapshot ready for ios https://github.com/tauri-apps/tauri/tree/feat/ios-build

This is awesome, I was thinking to learn Flutter before I saw this.

**Comment by sekwah41** [comment]
If you are focusing on mobile first @roldanjr you may also be interested in react-native using [expo](https://expo.dev/) (speeds up dev and is reccomended by the react site), flutter or [ionic](https://ionicframework.com/).

Also for now snap isnt supported by tauri though I will look into how to compile it for snap and either setup some stuff or try to work on adding support to tauri depending on the complexity >.> as there are already linux builders for AppImage and deb.

**Comment by sekwah41** [comment]
Ok ive started looking into rust and honestly, I wish id tried it earlier, once I am happy enough with it ill move onto tauri and start trying a migration.

Seems like a pretty good clean language as well as some very powerful libraries e.g. tauri.

**Comment by q-wertz** [comment]
Are there any news on this? Excited to see it  :)

**Comment by roldanjr** [comment]
> Are there any news on this? Excited to see it :)

@sekwah41 is trying to work on the Backend migrating it to Tauri while on my side, I'm trying to target Mobile, Web, and Desktop for the Frontend using React Native + Web. It will take a while before we release a new version of this app especially since we are just doing it in our own spare time but it's worth the effort.

**Comment by q-wertz** [comment]
Thanks for the info :blush: 
Really like the app and the design. Take your time :)

**Comment by sekwah41** [comment]
@roldanjr one thing you make like is tauri is aiming to allow iOS and android targets too. 

They have some in dev branches but if u remember correctly it's getting there.

**Comment by sekwah41** [comment]
https://tauri.app/v1/guides/distribution/sign-linux one issue there will be of using tauri is that it doenst have the same amount of linux targets as electron builder.

at minimum id like to support AppImage which seems possible and Snap which I will need to also investigate.

I will take a look into how close the mobile version platforms of tauri are to being ready but I may delay this until I've made changes to the frontend to support it running on [Ionic](https://ionicframework.com/) on mobile devices.

**Comment by sekwah41** [comment]
As long as the calls to the backend are non-implementation specific we can tinker with both at the same time even if it's just a testing branch or using it to cover the targets Tauri cant atm.

**Comment by sekwah41** [comment]
Actually because @roldanjr has used the default snap building mechanism rather than the electron builder output for snap solely hes actually possibly made it a lot easier to modify this to use Tauri for the snapcraft version.

**Comment by sekwah41** [comment]
Luckily it looks like you can also compile the windows binaries on on linux but itll probably be less fiddly to just compile on the correct platforms.

Just set up the base project today it seems to render fine at least. I will need to create a lost of all the features and issues that need to be implemented e.g. the fullscreen breaks or minimising to the tray.

While making these edits ill try to abstract it in some way so that the mobile version if we dont use Tauri also can hook into these same calls.

Though for the mobile version we will want flags to hide UI or alter it in ways.

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/209770142-9093dd70-fd3e-434f-ac3b-b87d9603601e.png)
The renderer obviously works fine as you can even run it in chrome. Though there is an odd flickering issue on majaro at least which seems to be a problem with webkit (see https://github.com/tauri-apps/tauri/issues/4236)

**Comment by sekwah41** [comment]
Will need to update some of the postbuild scripts for stuff like  the renderer to stop it from deleting files tauri wants. Also we should be copying from the other projects to here not the other way around.

**Comment by sekwah41** [comment]
Some of the tools only work on Ubuntu. I'll try to take a look at adding new targets for Tauri or adding to the project itself because id like to toy with more Linux things and expand my rust knowledge so once I have some other parts out of the way or hit a wall with this ill take a tinker with more underlying parts.

One user on that issue also reported that the compiled versions locally may not have that issue but inside app images it seems to be a problem.

**Comment by sekwah41** [comment]
I am temporarily disabling the main electron test build workflow while I test some tauri stuff just to avoid a lot of unneeded builds.

**Comment by sekwah41** [comment]
The flickering only seems to be in dev mode when resizing so feel free to ignore that on linux at least. The AppImage ive tested that it compiles seems to be fine.

**Comment by sekwah41** [comment]
So here are the tasks that still need to be done with the tauri version

- [ ] List the functions that need remaking in Tauri
- [ ] Connect the Frontend to the new rust backend calls
- [ ] Snap file output

**Comment by sekwah41** [comment]
I will check the ram usage, though 
![image](https://user-images.githubusercontent.com/3209834/209990495-0ffe59b3-4bd5-4d29-9976-1fec87efd3a9.png)
Not only would we lose output targets we can use. The bundle size for AppImage is around about the same. Ill need to check Win and Mac but the deb files are about 6MB instead. So it can be significantly smaller.

**Comment by sekwah41** [comment]
At least in appimage mode it seems to use a bit less memory as Tauri vs Electron (rough look id estimate electron uses 50% more minimum?). As the platform matures itll gain a lot more benefits, it seems we are losing a lot of key targets for linux, as well as

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/210021595-dc79667b-4cb1-48e8-ab73-56b126e4d0fb.png)
The sizes are a lot better on other platforms.

**Comment by sekwah41** [comment]
I am going to go ahead with making a Tauri version while maintaining the electron version for targets it doesn't currently support.

It would also be good to look into adding feature flags or settings for hiding or setting certain settings.

**Comment by sekwah41** [comment]
I will be continuing progress over here before cleaning up the commits https://github.com/sekwah41/pomatez-tauri

I've refactored the Electron context to allow a connector for us to properly talk to different platforms a bit easier.

**Comment by sekwah41** [comment]
As I'm also looking at a mobile version there is even more reason for me to progress this now. 

I have some base versions with tauri already but need to finish the implementations.

I've also raised some bugs I've found on linuxnwith tauri from doing this that seem to be fixed and merged too.

Mobile news for reference https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/

**Comment by roldanjr** [comment]
I'm actively revamping the project, making it more maintainable and scalable.
But in the meantime, I will still use Electron for packaging the app for the Desktop until all our target platforms are fully supported by Tauri or we can make a gradual transition after the whole revamp has been done.

For your reference, I'm working on this branch [revamp](https://github.com/roldanjr/pomatez/tree/revamp)

**Comment by sekwah41** [comment]
@roldanjr you may want to take a look at the renderer changes i made relating to connecting/communicating to the backend https://github.com/roldanjr/pomatez/tree/sekwah/tauri-tests/app/renderer/src/contexts

I abstracted it so we can support different platforms with the same frontend.

**Comment by roldanjr** [comment]
> @roldanjr you may want to take a look at the renderer changes I made relating to connecting/communicating to the backend https://github.com/roldanjr/pomatez/tree/sekwah/tauri-tests/app/renderer/src/contexts
> 
> I abstracted it so we can support different platforms with the same front end.
> 
> As long as that exists and works it doesn't matter what changes you make :p it should be fine :)

Yes, I'll consider this @sekwah41

**Comment by sekwah41** [comment]
Going to give this one another push, ill organise some time to work on it especially now that I've seen one of the apps i use called [Cider](https://cider.sh/) has updated to use it to quite a bit of success it seems :)

**Comment by sekwah41** [comment]
Relating to snap usage https://github.com/tauri-apps/tauri/pull/6532

**Comment by sekwah41** [comment]
Seems that tauri is now usable on mobile and in the next major release will fully support it. Though I have a test app working locally now. Could be something fun to explore on top of the desktop app once we have that ported over.

**Comment by roldanjr** [comment]
That sounds cool, I'm planning to learn rust also so I will know what's happening not just on the frontend side of the app.

**Comment by sekwah41** [comment]
![rustrover64_F5u2OQ6Pwh](https://github.com/zidoro/pomatez/assets/3209834/dcf40040-e97e-41c2-8057-6de35bb1a003)
Starting to get the features 1-1 with windows, though still a fair bit more to go.

**Comment by sekwah41** [comment]
You also get a few benefits from the current windows native browser

![image](https://github.com/zidoro/pomatez/assets/3209834/3c8e1aec-ecfb-470d-89f9-821f5b81cf63)


![image](https://github.com/zidoro/pomatez/assets/3209834/58c39d09-c78a-4650-b9d0-bc186453465d)

**Comment by sekwah41** [comment]
While there are still pieces to implement, ill make a list in the coming days, a large portion of it at least has been sorted.

Ive uploaded this zip file as a test in case anyone wants to try, though the code is available on the sekwah/tauri-test branch too.

Would be cool to also customise the installer with some screenshots or pieces about the app

https://tauri.app/v1/api/config/#nsisconfig
[Pomatez_1.3.0_x64_en-US.zip](https://github.com/zidoro/pomatez/files/12776007/Pomatez_1.3.0_x64_en-US.zip)


One example of a missing feature which wont be hard to add but still needs to be done is keeping the app open in the background when you click x.

**Comment by sekwah41** [comment]
Another difference ive made is the choice to always keep the system tray icon on as I often would use it as a quick glance. Also it doesn't seem to vanish when you maximise the app again on the electron version so I just kept it there to start.

**Comment by sekwah41** [comment]
![image](https://github.com/zidoro/pomatez/assets/3209834/8f7dce2e-da02-4bbc-b779-47b309b664b6)
![image](https://github.com/zidoro/pomatez/assets/3209834/ced0a32f-9863-4bf3-a666-f4153f80a9a8)

You can also do this with the electron builder installer. But I thought it would be interesting to try to customise the installer a bit.

Also we can build these and run on arm. Ive seen it run on my raspberry pi fine.

**Comment by sekwah41** [comment]
List of features still needed (not complete)

- [ ] Global hotkeys
- [ ] Voice assistance (update to tauri v2 for that fix)
- [ ] Allow Text fields to also select the native context menu (titles)
- [ ] Auto Updater

**Comment by sekwah41** [comment]
The downside is the auto-updater can't be hosted purely on GitHub releases as easily. However, we could make it push to an external server.

Though I am going to leave this all for another day because I have a lot of other things to sort out today sadly :(

**Comment by roldanjr** [comment]
> The downside is the auto-updater can't be hosted purely on GitHub releases as easily. However, we could make it push to an external server.
> 
> Though I am going to leave this all for another day because I have a lot of other things to sort out today sadly :(

That's alright @sekwah41 :) You've made a lot of effort on this, really appreciate it. Just take your time :D

**Comment by sekwah41** [comment]
We may also need to take a look at possibly finding a way to get the auto updater to also look at github, though may that have issues with the electron version? Ill check this all out once I've got the rest sorted.

**Comment by sekwah41** [comment]
This page will also help with info on the mobile parts https://beta.tauri.app/blog/tauri-2-0-0-alpha-4/#updating-dependencies

**Comment by sekwah41** [comment]
For anyone interested, I may have finished the port to Tauri aside from the auto-updater.

Test builds will be available here once its finished building

https://github.com/zidoro/pomatez/actions/runs/6619351140

**Comment by sekwah41** [comment]
I will take a look at how best to do the auto updater at some point, though when I can ill start doing tests on mac and linux.

**Comment by sekwah41** [comment]
So by default it cant handle just pulling the files from releases like electron builder. What ill do is take a look at adding that functionality either into the base updater or our app if we can control that to a more granular level.

**Comment by sekwah41** [comment]
So far, I absolutely love working with Rust. The ability to add extra functionality onto existing classes makes it really clean to make the setup tasks and avoid having to pass objects around anywhere near as much as something like node or java.

I am not sure what is considered best practice, though the modular way I am approaching this, I would like to say, is keeping the code maintainable and rather clean.

**Comment by sekwah41** [comment]
Ok, generating the updater file is a bit more complex than on electron-builder. Though I could make it do separate latest files like electron builder done. I will experiment with that first but explore using a final step to upload all the assets at once and create a single combined updater file outlined in the syntax here.

![image](https://github.com/zidoro/pomatez/assets/3209834/e70c22ac-4a97-4448-80c6-dc60847ad0d4)

I will once I've got past a certain point do some test releases on my own personal fork before publishing this.

However I need to switch focus onto an event for the beginning of November so I may not be able to progress this for a few weeks. Though I want to see this working as it feels so close!! :)

**Comment by sekwah41** [comment]
I will be testing and messing around with it over here https://github.com/sekwah41/pomatez so that I can do test releases as well as try to target multiple builds.

@roldanjr do you remember if anyone is using the 32bit versions of the apps? I see we build ia32 versions though I am not sure if any modern systems really use them anymore.

I will target x86_64 and arm64 though will try to set it up so we can expand it to add others easier to future proof it.

**Comment by sekwah41** [comment]
So there are issues currently with AppImage on arm64 and also you cant reliably to portable due to the MSI making sure some of the core windows features with the webview are installed https://github.com/tauri-apps/tauri/discussions/3048

**Comment by sekwah41** [comment]
One other cool thing we can do is compile a universal version for macos which can work on both intel and arm. 

I will steal a new MacBook from family to test these https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by sekwah41** [comment]
Will need to check on linux at some point properly, though at least in dev mode on my steam deck it crashes or just doesnt load. (if you comment out try_set_min_size to avoid the crash) so something seems to be freezing it so its not processing any commands.

**Comment by roldanjr** [comment]
> https://github.com/sekwah41/pomatez

I agree, I believe it's safe to omit the 32 bit format.

**Comment by sekwah41** [comment]
Looks like I'm almost there. Just need to debug info about the auto updaters and detecting if there is an update or not. I believe it may not be setting headers or something else because it's not detecting updates. 

If anyone wants to try the builds so far you can see them at https://github.com/sekwah41/pomatez/releases

Though I'll be trying to fix the auto updated over the next few days.

**Comment by sekwah41** [comment]
Ok so looks like the issues were due to a problem with github rejecting the headers. So I've fixed that and will look at making the pop up happen, but also possibly adding some UI to interact with updating.

This should also possibly have a button to ignore this update and remember to ignore that update.

**Comment by sekwah41** [comment]
We can implement this for the electron version too, though I am going to add some new UI which will show on the settings page when an update is available 
![image](https://github.com/zidoro/pomatez/assets/3209834/f71be8b7-b7be-4878-b074-cc0bd9bd5d6d)

**Comment by sekwah41** [comment]
![image](https://github.com/zidoro/pomatez/assets/3209834/638f6bbd-4f61-4d62-b061-e59f54683e48)

**Comment by roldanjr** [comment]
I'm good with this @sekwah41 🥇

**Comment by sekwah41** [comment]
While there is still work to be done, the base app for the tauri version is now working and will be released with the tag tauri-beta next to the file names.
