### ISSUE TITLE
pomatez.exe flagged in virus total

### ISSUE THREAD

**Issue by xJamayka** [zidoro/pomatez#329]
https://www.virustotal.com/gui/file/85fa93ae1cb1db40455f938719bcaa0cd0ea7a93e2aae3d364c09091fecb1fbb?nocache=1

**Comment by sekwah41** [comment]
Sometimes the installer can be flagged as that. I'll need to check if thats been flagged up on the electron-builder repo.

I've never heard of Gridinsoft tbh and it seems the only one flagging it up so it may not be raised as an issue. Itll be a false positive though usually if its widespread electron-builder do fix it.

**Comment by sekwah41** [comment]
As there don't seem to have been any more reports of this I will assume its gone :) Also it was only Gridinsoft
