### ISSUE TITLE
Arm64 Native Build For Windows

### ISSUE THREAD

**Issue by huangyinhaow** [zidoro/pomatez#343]
Windows computers with Arm SOC have a long battery life and now more and more people, especially teachers and students, are using these kind of computers and wnr is exactly what they need.
Thanks!

**Comment by sekwah41** [comment]
Sorry but github build actions do not currently support arm64 runners. Though I may be able to set up one of my raspberry pi’s or something to allow it. Though you will need to check what windows os you are using because certain versions can only use windows created executables.

I’ll need to see if the building tools support cross compiling. Luckily as I’ve been adding Tauri support we may have stuff there too.

**Comment by huangyinhaow** [comment]
I build [pomatez](https://github.com/roldanjr/pomatez) successfully in wsl.
![image](https://user-images.githubusercontent.com/64564727/224526955-9bda4e1d-be10-4e2e-b017-5f3fe7d01268.png)

**Comment by huangyinhaow** [comment]
Just add arm64 to package.json and it just work!
"https://github.com/huangyinhaow/pomatez-builds/releases/tag/latest

**Comment by sekwah41** [comment]
Oh is this the windows 11 arm preview?

As long as we add something to the name so there isnt a name clash it should be all fine :D

**Comment by huangyinhaow** [comment]
In your first coomment, you expressed your concern about the feasibility of cross-compiling, so I first tried a method that does not require cross-compiling, i.e. compiling in wsl on arm64. This method can successfully build pomatez, but not NSIS, so building it requires using wine32, which is not possible on the arm64 architecture This is not possible on the arm64 platform.

Next, I tried the second method. I forked the project, modified workflow.yml, and package.json, and luckily, it worked perfectly.

在您的第一个coomment中，你表达了你对于交叉编译的可行性的担忧，因此我首先尝试了一种不需要交叉编译的方法，即在arm64的wsl中编译，这一种方法可以成功构建出pomatez，但是无法构建出NSIS，因此构建它需要使用wine32，这在arm64架构的平台上是办不到的。

接着，我尝试了第二种方法。我fork了这个项目，修改了workflow.yml，和package.json，很幸运，这是完全可行的。

**Comment by huangyinhaow** [comment]
Notification is not working.
https://user-images.githubusercontent.com/64564727/224655298-f5bd0ea1-f622-43f7-8801-767aa0bcace4.mp4

**Comment by sekwah41** [comment]
Need to take more of a look, just been quite busy lately though there is also more news about  Microsoft and arm now so I will need to take more of a look.

**Comment by huangyinhaow** [comment]
Done in https://github.com/zidoro/pomatez/pull/376
