### ISSUE TITLE
Bug Report: Can not change config by touching

### ISSUE THREAD

**Issue by intzaaa** [zidoro/pomatez#344]
**Describe the bug**
Cannot use touch to change the config, the slide control seems to be unchecked.

**To Reproduce**

https://user-images.githubusercontent.com/64564727/224657639-1c8b0b4a-78a0-4471-b3ba-094153f2ed80.mp4

- OS: WIndows 11 22H2 arm64
- App Version 1.2.2
- Installer Used NSIS

**Comment by huangyinhaow** [comment]
Any update?

**Comment by roldanjr** [comment]
Hi @huangyinhaow, I tried to replicate this issue in Linux and it's currently functional but with some accessibility issues.

I believe this is a minor thing so, I will not add this to the priority. Rest assured that this issue will be addressed in the upcoming revamp version of the app that I am currently working on :)

**Comment by sekwah41** [comment]
I don't have an ARM windows machine though it would be handy if anyone else was able to verify this issue. I have a little windows laptop I can give it a go with when i get a moment.

**Comment by intzaaa** [comment]
Fixed
