### ISSUE TITLE
Bug Report: Open At Login not persistent

### ISSUE THREAD

**Issue by BitsInTheWilderness** [zidoro/pomatez#350]
When removing Pomatez from Open At Login system settings, it is automatically added back after restarting the app.

https://user-images.githubusercontent.com/1574985/232174277-71786af3-1b2e-4c49-bcc1-29cb7ce4319d.mov

**Comment by sekwah41** [comment]
I believe this may be a duplicate for #161. @roldanjr has a fix or is working on one I believe.

**Comment by sekwah41** [comment]
oh wait no wrong ticket. Ill update that, though we have one open.

**Comment by sekwah41** [comment]
Preferably it would listen to changes on the individual operating systems too, rater than force it on at every start.

Its only the initial start we need to set it on, though a toggle on the settings menu would work too.

**Comment by sekwah41** [comment]
While this isnt removed when you remove it from the system settings, you can now disable it from the app settings.

I will happily re-open this if it is still an issue :)
