### ISSUE TITLE
Suggestion: Ability to set longer focus time than 60 minutes

### ISSUE THREAD

**Issue by dolszewski97** [zidoro/pomatez#363]
Is there an ability to increase maximum value for Stay Focus selection? It can be useful for people which enjoys "working in flow state" like software developers. In my opinion maximum value of 120 minutes would be great.

**Comment by ziadevcom** [comment]
I am willing to fix this. Do you guys accept pull requests? I am sorry if this is not the right place to ask this.

**Comment by sekwah41** [comment]
yep we accept PR's :) @ziadevcom

**Comment by ziadevcom** [comment]
We can set the maximum focus time to 120 minutes but I have a question.
Should we keep the unit still in minutes? or we can change it to hours after 59 minutes?
In my opinion, it would be better keeping it minutes. It's a simpler approach and it does not really hurt UX. 
What do you think?

**Comment by sekwah41** [comment]
I think either one works, though changing the view to say 02:00:00 rather than 120:00 may be a bit strange. While it makes more sense based off how most time stuff displays, having it vanish once it goes sub 60 mins would be stranger.

**Comment by ziadevcom** [comment]
I have decided to go with default format of 120 minutes. I think that works just fine.

**Comment by sekwah41** [comment]
Actually, ive just made some css changes and it doesn't look that bad if we toggled it via  the max time 
![image](https://github.com/zidoro/pomatez/assets/3209834/b1b34f19-bf48-4b21-8d54-f7219f52057d)

**Comment by sekwah41** [comment]
I would personally prefer it like this, though @roldanjr is the main design guy on this :)

**Comment by ziadevcom** [comment]
Right, I will take a look at the timer component and understand how it works. I will get back to you soon.

**Comment by sekwah41** [comment]
Feel free to ask any questions or let me know if you need a hand; the only reason I haven't implemented this yet was I've just been quite pre-occupied with other projects and haven't got around to it :)

**Comment by ziadevcom** [comment]
Thank you, this won't be easy for me considering this is my first time contributing to open source but I am up for a challenge.

**Comment by sekwah41** [comment]
I see you are studying React and stream programming. Ill try to give you as much feedback as possible if I request changes ^.^

**Comment by ziadevcom** [comment]
I wanted to confirm but we still want to keep the unit in minutes on the config screen. right?

![image](https://github.com/zidoro/pomatez/assets/45315917/9e901939-19cf-4c73-bbca-258733e09ba4)

**Comment by roldanjr** [comment]
> I wanted to confirm but we still want to keep the unit in minutes on the config screen. right?
> 
> ![image](https://user-images.githubusercontent.com/45315917/239712716-9e901939-19cf-4c73-bbca-258733e09ba4.png)

Yes @ziadevcom just keep it in minutes unit :)

**Comment by roldanjr** [comment]
> Actually, ive just made some css changes and it doesn't look that bad if we toggled it via the max time ![image](https://user-images.githubusercontent.com/3209834/239709711-b1b34f19-bf48-4b21-8d54-f7219f52057d.png)
> 
> Basically, disable the grid display, remove grid-template-columns and text-align:center and its sorted.
> 
> As long as we reduce the margins between the span's which is what that does, though to keep the original look wed need to also optionally toggle some margin spacing depending on which one is being displayed.
> 
> ![image](https://user-images.githubusercontent.com/3209834/239709772-d3217a8d-5921-46d2-9734-75bc7346a4f2.png)

I'm okay with this @sekwah41, I'll figure out next time in v2 how to address the design for this scenario.
