### ISSUE TITLE
Bug Report: Can drag navbar links

### ISSUE THREAD

**Issue by sekwah41** [zidoro/pomatez#378]
![image](https://github.com/zidoro/pomatez/assets/3209834/270d8470-30b5-475a-9be4-a1894b03cf9e)

Dragging the nav buttons at least drags the URL's. While we want to allow this for url's in tasks and other places these sorts of ones we should disable it for these.

- OS: Manjaro Linux
- App Version 1.2.3
- Snap

**Comment by ziadevcom** [comment]
I am willing to fix this one as well. We just need to add `draggable="false"` attribute to the links. Tho, I am not sure if making a separate branch for a small fix like this would be a good idea. Might be a good option to fix this in another hotfixes PR like you guys did before. 

I am not sure, what do you guys think?

**Comment by roldanjr** [comment]
You can create a `hotfix/{name-of-the-issue}` branch from this repo and after fixing the issue you can submit a PR using that branch. Just make sure to properly follow the conventional commit message :)
