### ISSUE TITLE
Bug Report: 1.3.0 Javascript error

### ISSUE THREAD

**Issue by DoctorDinosaur** [zidoro/pomatez#411]
Updated from 1.2.3

Now, upon launching, I get this popup:

![image](https://github.com/zidoro/pomatez/assets/26852749/038c1dd7-5077-41c1-94b9-d512a4122eae)

**Comment by CptDinosaur** [comment]
I turned on and off the new "Open at Login" slider and the error went away. So I assume it's related.

**Comment by roldanjr** [comment]
Hi @CptDinosaur did you try to turn on the `Open at Login` and check if the error persists?

**Comment by CptDinosaur** [comment]
Turning on Open at Login doesn't bring the error back.

Though, turning it off didn't actually remove its startup entry
![image](https://github.com/zidoro/pomatez/assets/26852749/871f66c1-7dfd-4515-99b9-4532260a1712)

**Comment by rfiedorowicz** [comment]
I had a similar situation,

reproduce steps:
- have installed 1.2.3
- install 1.3.0
- got that error (just after installation)

after turn off the 'open at login' the app stills opens so I manually deleted it from startup apps (windows 11)

Now everything working fine.

**Comment by davidbgonz** [comment]
I have the same error on Arch Linux with Nodejs v18.17.0 (using nvm). There is no "Open on Login" option for the Linux version. When I first updated the application, the "Notification Types" section got reset with no default selected. When I selected one of the types it was okay, but only for that session. Today when I started up the app the same error popped up again.

**Comment by sekwah41** [comment]
@davidbgonz on linux there should be an on start list, I know on manjaro with plasma its quite easy but not too sure about your specific setup.

**Comment by davidbgonz** [comment]
I’m running i3. I specify start on boot in the config in i3. I was just giving extra information that the error still appears despite there being an open in login option.

**Comment by sekwah41** [comment]
This is an issue with an  underlying library. I am going to create a safe wrapper to ensure the errors to not propagate.

https://github.com/ipfs/ipfs-desktop/issues/2336 this is the same issue

**Comment by sekwah41** [comment]
Sorry for not releasing this, it should be in the next update.

**Comment by sekwah41** [comment]
I believe this is fixed
