### ISSUE TITLE
Disable Auto Open Github Repo Everytime machine starts

### ISSUE THREAD

**Issue by eyobtilahun** [zidoro/pomatez#447]
I am using pomatez version 1.2.2 and as it gets an updates.it will automatically open the GitHub repo where I can get an update for download. but i want to keep my current version and don't want to update to the latest version.is there any way where i can stop auto opening my browser every time i start my machine(pc)

**Comment by sekwah41** [comment]
It was never meant to open your browser every time vs just alert you, I think there was an issue with the previous version. The latest from the tests I've done when its released should no longer have that issue.

**Comment by sekwah41** [comment]
I believe this should be fixed, we also have a tauri version now that you can ignore updates until the next update comes out too :)
