### ISSUE TITLE
Publish to WinGet CI job fails

### ISSUE THREAD

**Issue by ottnorml** [zidoro/pomatez#477]
@roldanjr As you may have noticed, the `Publish to WinGet` CI job failed with the following error message when version 1.3.1 was released (see [log](https://github.com/zidoro/pomatez/actions/runs/6600322601/job/17930298562#step:2:84)):
> Fork of winget-pkgs not found. Forking...
> Failed to fork winget-pkgs. Please try again or fork it manually

The easiest way to prevent this message from appearing again, and to fix the error, is to fork the [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) repo in the `zidoro` organization.

Otherwise code and configuration changes are required as the github action options `fork-user` and `token` must be overridden to set the new location of the fork and provide access to it (see [documentation](https://github.com/vedantmgoyal2009/winget-releaser/blob/84d403a75da1f2df4ab82216ef48f7453f6e9e1d/README.md?plain=1#L180-L183)).

Refs https://github.com/microsoft/winget-pkgs/issues/124301, https://github.com/microsoft/winget-pkgs/pull/124334

**Comment by roldanjr** [comment]
I forked it @ottnorml https://github.com/zidoro/winget-pkgs :)

**Comment by jnm2** [comment]
Something is still not working. v1.6.0 and v1.6.1 have not been published to https://github.com/Microsoft/winget-pkgs/tree/master/manifests/z/Zidoro/Pomatez.
