### ISSUE TITLE
Publish to WinGet CI job fails again (1.6.0+ are missing)

### ISSUE THREAD

**Issue by jnm2** [zidoro/pomatez#545]
Following up from https://github.com/zidoro/pomatez/issues/477#issuecomment-1828435619 (@roldanjr, @ottnorml)

Latest error:
> Failed to create branch from upstream default branch

https://github.com/zidoro/pomatez/actions/runs/6975149239/job/18981961095 by @sekwah41

**Comment by sekwah41** [comment]
I havent used winget before, though taking a look at some of the setup steps for https://github.com/vedantmgoyal2009/winget-releaser i assume its because whoever configured it is trying to use the github access token rather than a PAT token for a user account.

Also it looks like the fork-user isn't setup for the action.

**Comment by jnm2** [comment]
@sekwah41 Ah, my mistake. The commit messages in the recent job runs looked like you may have been working with it.

**Comment by sekwah41** [comment]
I will try to sort it for the next release, though I will take a look at doing a manual pr to update it for now.

**Comment by sekwah41** [comment]
And another failure T^T 0 clue why that failed if we had one run fine in the past

**Comment by sekwah41** [comment]
Ok looks like the config is fine for making the branch with the edits on, so ill try to configure whats wrong over a few updates but manually trigger the pr side of things.

**Comment by sekwah41** [comment]
Oh no it does look like the pr is opened https://github.com/microsoft/winget-pkgs/pull/130120. Not sure why it showed as it failed

**Comment by sekwah41** [comment]
Should be sorted now, i will manually deploy when they are not working :)
