### ISSUE TITLE
Bug Report: Mac ARM version says it is damaged

### ISSUE THREAD

**Issue by ajfriesen** [zidoro/pomatez#570]
**Describe the bug**
Can not install the latest version on Macbook M1 Pro. App says it is damaged.

**To Reproduce**
Steps to reproduce the behavior. Example:

1. Download: [Pomatez-v1.6.2-mac-arm64.dmg](https://github.com/zidoro/pomatez/releases/download/v1.6.2/Pomatez-v1.6.2-mac-arm64.dmg)
2. Try to install
Will fail and tell you that the app is damaged.

> “Pomatez.app” is damaged and can’t be opened. You should move it to the Bin.

**Expected behavior**
It should be able to start.

**Desktop (please complete the following information):**

- OS: Mac 14.2 (23C64)
- App Version: [Pomatez-v1.6.2-mac-arm64.dmg](https://github.com/zidoro/pomatez/releases/download/v1.6.2/Pomatez-v1.6.2-mac-arm64.dmg)

**Comment by sekwah41** [comment]
Will check when I'm back tonight or tomorrow. I've been mostly focusing on the Tauri version but I believe electron was working (local builds at least) as I've just been adding apple codesigning to both.

Thanks for flagging this up :)

**Comment by sekwah41** [comment]
Hopefully the next release should fix that, ive also added apple code signing!

**Comment by sekwah41** [comment]
@ajfriesen can you give the most recent release a go?

**Comment by ajfriesen** [comment]
Seems to be fixed, Thank you   :)
