### ISSUE TITLE
Does not go fullscreen on Windows

### ISSUE THREAD

**Issue by MariusDrulea** [zidoro/pomatez#596]
I do use the app on both Ubuntu and Windows 10. Works perfectly in Ubuntu, when the timer ends the fullscreen is taken and I'm forced to take the break. In Windows 10 however, the application fails to go fullscreen when the timer ends. And I have to click on the app one more time for this to happen - see the highlighted pomatez icon in the picture bellow.

![image](https://github.com/zidoro/pomatez/assets/27725572/0e66e335-029a-4fef-8d64-3e6dcfa3b425)

**Comment by sekwah41** [comment]
Are you using the Tauri beta or the main electron release?

**Comment by MariusDrulea** [comment]
I do use the release: https://github.com/roldanjr/pomatez/releases/download/v1.6.4/Pomatez-v1.6.4-win-x64-setup.exe
An update: If I set the app to be "always on top" than it will go "mostly" fullscreen: covers everything except the task-bar.

**Comment by MariusDrulea** [comment]
Works well if I disable the native title bar.
